name: Build and Push Docker Image


# This workflow is manually triggered from the "Actions" tab in GitHub.
# It requires a single input: the version tag of the flood repository to use.
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Image name
      run: |
        echo "IMAGE_NAME=k2patel/rtorrent:latest" >> $GITHUB_ENV

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build the Docker image
      id: build
      run: |
        docker build . -t ${{ env.IMAGE_NAME }}:latest

    - name: Push the Docker image
      run: docker push ${{ env.IMAGE_NAME }}